#!/bin/bash

debug() { echo "$@" 1>&2; }

#HTPASS_DIR=/etc/nginx/htpasswd
HTPASS_DIR=.
SITES_DIR=$HTPASS_DIR/sites
SITES_DIR_FORMAT="$SITES_DIR/.%s.rules"

if [ "$(id -u)" != "0" ];
then
    echo "Error; Must run as root."
fi

mkdir -p $HTPASS_DIR 
mkdir -p $SITES_DIR 


case $1 in
    siteadd )
	arg=$(printf $SITES_DIR_FORMAT $2)
	touch $arg
	;;
    sitedel )
	arg=$(printf $SITES_DIR_FORMAT $2)
	rm $arg
	;;
esac

