#!/bin/bash

debug() { echo "$@" 1>&2; }

#HTPASS_DIR=/etc/nginx/htpasswd
HTPASS_DIR=.
SITES_DIR=$HTPASS_DIR/sites
SITES_DIR_FORMAT="$SITES_DIR/.%s.rules"
USER_DIR=$HTPASS_DIR/users
USER_DIR_FORMAT="$USER_DIR/%s"
TMP_FILE=/tmp/nggrouptmp

if [ "$(id -u)" != "0" ];
then
    echo "Error; Must run as root."
fi

mkdir -p $HTPASS_DIR
mkdir -p $SITES_DIR
mkdir -p $USER_DIR

case $1 in
    siteadd )
	touch $(printf $SITES_DIR_FORMAT $2)
	;;
    sitedel )
	rm $(printf $SITES_DIR_FORMAT $2)
	;;

    
    useradd )
	file=$(printf $USER_DIR_FORMAT $2)
	contents=$(htpasswd -nb $2 $3)
	if [ -e $file ];
	then
	    echo "Error: user already exists."
	    exit 1
	fi

	echo $contents > $file
	;;

esac

