#!/usr/bin/env bash
# ignore $1

. $(dirname $0)/../email_config

    
emails_list=$(emails '' list all)
all_emails="${emails_list// /;}"

case $2 in
start )
    # downtime is starting
    downtime_start=$3
    downtime_end=$4
    send_email "" "Server downtime" \
	"<p>Dear all,</p>

e note that <em>${NGGROUP_SERVER_NAME}</em> is going to be down for maintenance between <strong>${downtime_start}</strong> and <strong>${downtime_end}</strong>. Further emails may follow with updates. </p>
OUP_SERVER_ADMIN_EMAIL" "set priority=high" "$all_emails"
    ;;
stop )
    # server coming back
    send_email "" "Server downtime" \
	"<p>Dear all,</p>

e note that <em>${NGGROUP_SERVER_NAME}</em> is back up following maintenance. </p>
OUP_SERVER_ADMIN_EMAIL" "set priority=high" "$all_emails"
    ;;
esac

