#!/usr/bin/env bash
# ignore $1

. $(dirname $0)/../email_config

NGGROUP_EMAIL_ADDRESS="$2"
NGGROUP_EMAIL_NAME="$3"
NGGROUP_EMAIL_USERNAME="$4"
NGGROUP_EMAIL_PASSWORD="$5"
NGGROUP_EMAIL_LINKS=()
NGGROUP_EMAIL_LINKS_COUNT=0
NGGROUP_SERVER_ADMIN_EMAIL_LINK=$(as_mail_link $NGGROUP_SERVER_ADMIN_EMAIL)
for link in $6;
do
    NGGROUP_EMAIL_LINKS[$NGGROUP_EMAIL_LINKS_COUNT]=$(as_li "$(as_link $link)")
    NGGROUP_EMAIL_LINKS_COUNT=$(( $NGGROUP_EMAIL_LINKS_COUNT + 1 ))
done

send_email "$NGGROUP_EMAIL_ADDRESS" "[${NGGROUP_SERVER_NAME}] Login details for ${NGGROUP_EMAIL_NAME}" \
"<p>Hi ${NGGROUP_EMAIL_NAME},</p>

<p>Please find attached your login details for <em>${NGGROUP_SERVER_NAME}</em>.</p>

<p>Details are as follows:</p>
<ul>
    <li>Username: <code>${NGGROUP_EMAIL_USERNAME}</code></li>
    <li>Password: <code>${NGGROUP_EMAIL_PASSWORD}</code></li>
</ul>

" "$NGGROUP_SERVER_ADMIN_EMAIL"

